//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivityTracking.WebClient.EPEServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://iepe100.isd.dp.ua/IsdData", ConfigurationName="EPEServiceReference.IsdDataWebServiceSoap")]
    public interface IsdDataWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iepe100.isd.dp.ua/IsdData/GetOfficeDataEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetOfficeDataEx(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iepe100.isd.dp.ua/IsdData/GetOfficeDataEx", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetOfficeDataExAsync(string login);
        
        // CODEGEN: Parameter 'GetPhotoResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://iepe100.isd.dp.ua/IsdData/GetPhoto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ActivityTracking.WebClient.EPEServiceReference.GetPhotoResponse GetPhoto(ActivityTracking.WebClient.EPEServiceReference.GetPhotoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iepe100.isd.dp.ua/IsdData/GetPhoto", ReplyAction="*")]
        System.Threading.Tasks.Task<ActivityTracking.WebClient.EPEServiceReference.GetPhotoResponse> GetPhotoAsync(ActivityTracking.WebClient.EPEServiceReference.GetPhotoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iepe100.isd.dp.ua/IsdData/GetInOutDataByLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetInOutDataByLogin(string login, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iepe100.isd.dp.ua/IsdData/GetInOutDataByLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetInOutDataByLoginAsync(string login, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iepe100.isd.dp.ua/IsdData/GetIsdEmployeeOfficeData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetIsdEmployeeOfficeData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iepe100.isd.dp.ua/IsdData/GetIsdEmployeeOfficeData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetIsdEmployeeOfficeDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iepe100.isd.dp.ua/IsdData/GetIsdEmplDataByLoginOrDepartment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetIsdEmplDataByLoginOrDepartment(string login, string team, string department, System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iepe100.isd.dp.ua/IsdData/GetIsdEmplDataByLoginOrDepartment", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetIsdEmplDataByLoginOrDepartmentAsync(string login, string team, string department, System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iepe100.isd.dp.ua/IsdData/GetThisDayTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetThisDayTime(string login, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iepe100.isd.dp.ua/IsdData/GetThisDayTime", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetThisDayTimeAsync(string login, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iepe100.isd.dp.ua/IsdData/GetSubordinateList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSubordinateList(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iepe100.isd.dp.ua/IsdData/GetSubordinateList", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetSubordinateListAsync(string login);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPhoto", WrapperNamespace="http://iepe100.isd.dp.ua/IsdData", IsWrapped=true)]
    public partial class GetPhotoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iepe100.isd.dp.ua/IsdData", Order=0)]
        public string login;
        
        public GetPhotoRequest() {
        }
        
        public GetPhotoRequest(string login) {
            this.login = login;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPhotoResponse", WrapperNamespace="http://iepe100.isd.dp.ua/IsdData", IsWrapped=true)]
    public partial class GetPhotoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iepe100.isd.dp.ua/IsdData", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetPhotoResult;
        
        public GetPhotoResponse() {
        }
        
        public GetPhotoResponse(byte[] GetPhotoResult) {
            this.GetPhotoResult = GetPhotoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsdDataWebServiceSoapChannel : ActivityTracking.WebClient.EPEServiceReference.IsdDataWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsdDataWebServiceSoapClient : System.ServiceModel.ClientBase<ActivityTracking.WebClient.EPEServiceReference.IsdDataWebServiceSoap>, ActivityTracking.WebClient.EPEServiceReference.IsdDataWebServiceSoap {
        
        public IsdDataWebServiceSoapClient() {
        }
        
        public IsdDataWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsdDataWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsdDataWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsdDataWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetOfficeDataEx(string login) {
            return base.Channel.GetOfficeDataEx(login);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetOfficeDataExAsync(string login) {
            return base.Channel.GetOfficeDataExAsync(login);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ActivityTracking.WebClient.EPEServiceReference.GetPhotoResponse ActivityTracking.WebClient.EPEServiceReference.IsdDataWebServiceSoap.GetPhoto(ActivityTracking.WebClient.EPEServiceReference.GetPhotoRequest request) {
            return base.Channel.GetPhoto(request);
        }
        
        public byte[] GetPhoto(string login) {
            ActivityTracking.WebClient.EPEServiceReference.GetPhotoRequest inValue = new ActivityTracking.WebClient.EPEServiceReference.GetPhotoRequest();
            inValue.login = login;
            ActivityTracking.WebClient.EPEServiceReference.GetPhotoResponse retVal = ((ActivityTracking.WebClient.EPEServiceReference.IsdDataWebServiceSoap)(this)).GetPhoto(inValue);
            return retVal.GetPhotoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ActivityTracking.WebClient.EPEServiceReference.GetPhotoResponse> ActivityTracking.WebClient.EPEServiceReference.IsdDataWebServiceSoap.GetPhotoAsync(ActivityTracking.WebClient.EPEServiceReference.GetPhotoRequest request) {
            return base.Channel.GetPhotoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ActivityTracking.WebClient.EPEServiceReference.GetPhotoResponse> GetPhotoAsync(string login) {
            ActivityTracking.WebClient.EPEServiceReference.GetPhotoRequest inValue = new ActivityTracking.WebClient.EPEServiceReference.GetPhotoRequest();
            inValue.login = login;
            return ((ActivityTracking.WebClient.EPEServiceReference.IsdDataWebServiceSoap)(this)).GetPhotoAsync(inValue);
        }
        
        public System.Data.DataSet GetInOutDataByLogin(string login, System.DateTime date) {
            return base.Channel.GetInOutDataByLogin(login, date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetInOutDataByLoginAsync(string login, System.DateTime date) {
            return base.Channel.GetInOutDataByLoginAsync(login, date);
        }
        
        public System.Data.DataSet GetIsdEmployeeOfficeData() {
            return base.Channel.GetIsdEmployeeOfficeData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetIsdEmployeeOfficeDataAsync() {
            return base.Channel.GetIsdEmployeeOfficeDataAsync();
        }
        
        public System.Data.DataSet GetIsdEmplDataByLoginOrDepartment(string login, string team, string department, System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.GetIsdEmplDataByLoginOrDepartment(login, team, department, fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetIsdEmplDataByLoginOrDepartmentAsync(string login, string team, string department, System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.GetIsdEmplDataByLoginOrDepartmentAsync(login, team, department, fromDate, toDate);
        }
        
        public string GetThisDayTime(string login, System.DateTime date) {
            return base.Channel.GetThisDayTime(login, date);
        }
        
        public System.Threading.Tasks.Task<string> GetThisDayTimeAsync(string login, System.DateTime date) {
            return base.Channel.GetThisDayTimeAsync(login, date);
        }
        
        public System.Data.DataSet GetSubordinateList(string login) {
            return base.Channel.GetSubordinateList(login);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetSubordinateListAsync(string login) {
            return base.Channel.GetSubordinateListAsync(login);
        }
    }
}
